### ISSUE TITLE
Current implementation will be errored when huge buffers

### ISSUE THREAD

**Issue by Shougo** [matsui54/ddc-buffer#1]
https://github.com/Shougo/ddc.vim/issues/30

https://github.com/matsui54/ddc-buffer/blob/main/denops/ddc/sources/buffer.ts#L50

It gets whole buffer lines by one RPC.
It exceeds current RPC in/out buffer(probably `65535`).

You need to use multiple RPCs like deoplete.

```python
def getlines(vim: Nvim, start: int = 1,
             end: typing.Union[int, str] = '$') -> typing.List[str]:
    if end == '$':
        end = len(vim.current.buffer)
    max_len = min([int(end) - start, 5000])
    lines: typing.List[str] = []
    current = start
    while current <= int(end):
        # Skip very long lines
        lines += [x for x in vim.call('getline', current, current + max_len)
                  if len(x) < 300]
        current += max_len + 1
    return lines
```

**Comment by Shougo** [comment]
The implementation is here.

https://github.com/Shougo/ddc-around/blob/57595f01fc10a33beadd1e146a3323eaaf1d697a/denops/ddc/sources/around.ts

**Comment by matsui54** [comment]
Thanks! I fixed. Can you check it?

**Comment by Shougo** [comment]
Thanks.  I will check it later.

**Comment by Shougo** [comment]
Thanks.  It seems good.

**Comment by matsui54** [comment]
Thank you for checking.
