### ISSUE TITLE
Enhancement: Add file/path completion source for ddc.vim

### ISSUE THREAD

**Issue by krisfans** [matsui54/ddc-buffer#5]
Can you add file/path completion source for ddc.vim?

**Comment by matsui54** [comment]
Sorry, I won't make file source. It's very difficult.
Why don't you make it? There are many examples.
https://github.com/hrsh7th/cmp-buffer
https://github.com/neoclide/coc.nvim/blob/master/src/sources/native/file.ts
https://github.com/Shougo/deoplete.nvim/blob/master/rplugin/python3/deoplete/source/file.py
